# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getcored.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1010, 673)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(501, 421))
        self.groupBox_2.setMaximumSize(QtCore.QSize(501, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setGeometry(QtCore.QRect(10, 30, 480, 320))
        self.frame.setMinimumSize(QtCore.QSize(480, 320))
        self.frame.setMaximumSize(QtCore.QSize(480, 320))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setObjectName("widget_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setGeometry(QtCore.QRect(100, 50, 256, 192))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 360, 94, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 390, 94, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 360, 94, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 390, 51, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 360, 51, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 360, 51, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(330, 390, 167, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_3.setMinimumSize(QtCore.QSize(111, 0))
        self.spinBox_3.setMaximumSize(QtCore.QSize(111, 16777215))
        self.spinBox_3.setMaximum(1000000000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_2.addWidget(self.spinBox_3)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 41))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4.addWidget(self.widget_4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(501, 121))
        self.groupBox.setMaximumSize(QtCore.QSize(501, 121))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(420, 90, 71, 25))
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(372, 30, 121, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(370, 90, 41, 25))
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(322, 60, 171, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(11, 30, 331, 28))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.widget1)
        self.spinBox.setMinimumSize(QtCore.QSize(81, 26))
        self.spinBox.setMaximumSize(QtCore.QSize(81, 26))
        self.spinBox.setMaximum(1000000000)
        self.spinBox.setProperty("value", 100)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget1)
        self.spinBox_2.setMinimumSize(QtCore.QSize(81, 26))
        self.spinBox_2.setMaximumSize(QtCore.QSize(81, 26))
        self.spinBox_2.setMaximum(1000000000)
        self.spinBox_2.setProperty("value", 100)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout.addWidget(self.spinBox_2)
        self.widget2 = QtWidgets.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(10, 60, 301, 28))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinBox_11 = QtWidgets.QSpinBox(self.widget2)
        self.spinBox_11.setMinimumSize(QtCore.QSize(81, 26))
        self.spinBox_11.setMaximumSize(QtCore.QSize(81, 26))
        self.spinBox_11.setMaximum(1000000000)
        self.spinBox_11.setProperty("value", 0)
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_4.addWidget(self.spinBox_11)
        self.label_10 = QtWidgets.QLabel(self.widget2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.spinBox_12 = QtWidgets.QSpinBox(self.widget2)
        self.spinBox_12.setMinimumSize(QtCore.QSize(81, 26))
        self.spinBox_12.setMaximumSize(QtCore.QSize(81, 26))
        self.spinBox_12.setMaximum(1000000000)
        self.spinBox_12.setProperty("value", 0)
        self.spinBox_12.setObjectName("spinBox_12")
        self.horizontalLayout_4.addWidget(self.spinBox_12)
        self.widget3 = QtWidgets.QWidget(self.groupBox)
        self.widget3.setGeometry(QtCore.QRect(10, 90, 151, 28))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget3)
        self.spinBox_4.setMaximum(360)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_3.addWidget(self.spinBox_4)
        self.widget4 = QtWidgets.QWidget(self.groupBox)
        self.widget4.setGeometry(QtCore.QRect(170, 90, 172, 31))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget4)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 26))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget4)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 26))
        self.pushButton_8.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(501, 121))
        self.groupBox_4.setMaximumSize(QtCore.QSize(501, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_12.setGeometry(QtCore.QRect(400, 30, 89, 25))
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 60, 161, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.widget5 = QtWidgets.QWidget(self.groupBox_4)
        self.widget5.setGeometry(QtCore.QRect(10, 90, 169, 28))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinBox_7 = QtWidgets.QSpinBox(self.widget5)
        self.spinBox_7.setMaximum(1000000000)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_6.addWidget(self.spinBox_7)
        self.widget6 = QtWidgets.QWidget(self.groupBox_4)
        self.widget6.setGeometry(QtCore.QRect(10, 30, 140, 28))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.spinBox_8 = QtWidgets.QSpinBox(self.widget6)
        self.spinBox_8.setMaximum(360)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_7.addWidget(self.spinBox_8)
        self.widget7 = QtWidgets.QWidget(self.groupBox_4)
        self.widget7.setGeometry(QtCore.QRect(160, 30, 224, 28))
        self.widget7.setObjectName("widget7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.widget7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.spinBox_9 = QtWidgets.QSpinBox(self.widget7)
        self.spinBox_9.setMaximum(360)
        self.spinBox_9.setProperty("value", 0)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_8.addWidget(self.spinBox_9)
        self.label_11 = QtWidgets.QLabel(self.widget7)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.spinBox_10 = QtWidgets.QSpinBox(self.widget7)
        self.spinBox_10.setMaximum(360)
        self.spinBox_10.setProperty("value", 180)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_8.addWidget(self.spinBox_10)
        self.widget8 = QtWidgets.QWidget(self.groupBox_4)
        self.widget8.setGeometry(QtCore.QRect(10, 60, 307, 28))
        self.widget8.setObjectName("widget8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.widget8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.spinBox_13 = QtWidgets.QSpinBox(self.widget8)
        self.spinBox_13.setMinimumSize(QtCore.QSize(81, 26))
        self.spinBox_13.setMaximumSize(QtCore.QSize(81, 26))
        self.spinBox_13.setMaximum(1000000000)
        self.spinBox_13.setProperty("value", 100)
        self.spinBox_13.setObjectName("spinBox_13")
        self.horizontalLayout_9.addWidget(self.spinBox_13)
        self.label_12 = QtWidgets.QLabel(self.widget8)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.spinBox_14 = QtWidgets.QSpinBox(self.widget8)
        self.spinBox_14.setMinimumSize(QtCore.QSize(81, 26))
        self.spinBox_14.setMaximumSize(QtCore.QSize(81, 26))
        self.spinBox_14.setMaximum(1000000000)
        self.spinBox_14.setProperty("value", 100)
        self.spinBox_14.setObjectName("spinBox_14")
        self.horizontalLayout_9.addWidget(self.spinBox_14)
        self.widget9 = QtWidgets.QWidget(self.groupBox_4)
        self.widget9.setGeometry(QtCore.QRect(190, 90, 301, 31))
        self.widget9.setObjectName("widget9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self.widget9)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget9)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 26))
        self.pushButton_9.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_10.addWidget(self.pushButton_9)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "视频显示"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">视频显示区域（480*320）</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">数据采集工具：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 数据量很大，成千上万都有可能</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.数据格式要求一至（大小，位置）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">思考如何批量获取大量数据</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("Form", "打开摄像头"))
        self.pushButton_2.setText(_translate("Form", "关闭摄像头"))
        self.pushButton_3.setText(_translate("Form", "视频文件"))
        self.pushButton_4.setText(_translate("Form", "预览"))
        self.pushButton_5.setText(_translate("Form", "开始"))
        self.pushButton_6.setText(_translate("Form", "暂停"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"right\">帧数：</p></body></html>"))
        self.groupBox_3.setTitle(_translate("Form", "预览区域"))
        self.groupBox.setTitle(_translate("Form", "预览设置"))
        self.pushButton_10.setText(_translate("Form", "局部预览"))
        self.lineEdit_2.setText(_translate("Form", "100*100"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"right\">缩放尺寸(像素W*H)：</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">*</p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"right\">旋转中心(X*Y)：</p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\">*</p></body></html>"))
        self.label_9.setText(_translate("Form", "旋转角度："))
        self.pushButton_7.setText(_translate("Form", "水平镜像"))
        self.pushButton_8.setText(_translate("Form", "垂直镜像"))
        self.groupBox_4.setTitle(_translate("Form", "保存设置"))
        self.label_4.setText(_translate("Form", "数量："))
        self.label_5.setText(_translate("Form", "旋转角度："))
        self.label_6.setText(_translate("Form", "旋转范围："))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\">---</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"right\">大小(像素W*H)：</p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\">*</p></body></html>"))
        self.pushButton_9.setText(_translate("Form", "保存"))

